// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgvPD1aFXy1lPC8tmZFDxbUpXsz9Mymnw',
    appId: '1:876119500188:web:7a904414102d62e29b9459',
    messagingSenderId: '876119500188',
    projectId: 'app-manage-2f6e0',
    authDomain: 'app-manage-2f6e0.firebaseapp.com',
    storageBucket: 'app-manage-2f6e0.firebasestorage.app',
    measurementId: 'G-CG96LZ1SMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWRIwYHs2yvT4j9LMbxUHQBDXY76bJ72o',
    appId: '1:876119500188:android:48b7093333421d7a9b9459',
    messagingSenderId: '876119500188',
    projectId: 'app-manage-2f6e0',
    storageBucket: 'app-manage-2f6e0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA250xPrWJmtpY3hB6DyQj-mV-NY0Wlf-c',
    appId: '1:876119500188:ios:9fbd1d83ac16c9759b9459',
    messagingSenderId: '876119500188',
    projectId: 'app-manage-2f6e0',
    storageBucket: 'app-manage-2f6e0.firebasestorage.app',
    androidClientId: '876119500188-51jiic0ad4qmtrcg0t54ff4kvo9rt86n.apps.googleusercontent.com',
    iosClientId: '876119500188-gfhc2cvhvne07lal5tflt413kqqv8l8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.craftyBay',
  );
}
